---
title: "exp11_analysis"
author: "Marcela Morassi"
date: '2022-04-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp11 <- read.csv("exp11_data.csv")
```

Data Manipulation
```{r}
#turning data discrete
exp11 <- exp11 %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==5, root>0) %>% 
  mutate(genotype = factor(genotype, levels = c("WT", "KO", "OX"))) %>% 
  mutate(ATP_conc = factor(ATP_conc, levels = c("0", "10", "200")))


#SE
exp11_SE <- exp11 %>% 
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))
```

t-tests
```{r}
#Marcela final root length
#WT control vs. 10
t.test(root ~ ATP_conc, genotype=="WT" & (ATP_conc == 0 | ATP_conc ==10), data = exp11, var.equal=FALSE, conf.level=0.95)
#t = -3.8551, df = 37.758, p-value = 0.0004359
#WT control vs. 200
t.test(root ~ ATP_conc, genotype=="WT" & (ATP_conc == 0 | ATP_conc ==200), data = exp11, var.equal=FALSE, conf.level=0.95)
#t = -0.030786, df = 32.029, p-value = 0.9756
#KO control vs. 10
t.test(root ~ ATP_conc, genotype=="KO", data = exp11, var.equal=FALSE, conf.level=0.95)
#t = 3.925, df = 38.5, p-value = 0.0003474
#OX control vs. 10
t.test(root ~ ATP_conc, genotype=="OX", data = exp11, var.equal=FALSE, conf.level=0.95)
#t = 5.4108, df = 22.447, p-value = 1.834e-05

exp11 %>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="137.5") %>% 
  summary()


```

Data Visualization
```{r}


##Final root length
#Marcela
ggplot(exp11_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  scale_x_discrete(labels = c("WT", expression(italic("dorn1-1")), "OX"))+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Dark2", name = "[ATP] (µM)", labels=c("Control", "10", "200"))
ggsave("exp6_m_finalgrowth.png")
```


