---
title: "exp10_analysis"
author: "Marcela Morassi"
date: '2022-04-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp10 <- read.csv("exp10_data.csv")
```

Data Manipulation
```{r}
#turning data discrete
exp10_data <- exp10 %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==5, root>0) %>% 
  mutate(genotype = factor(ATP_conc, levels = c("0", "0.5", "1", "2", "10", "20")))


#SE
exp10_SE <- exp10_data %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>%
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))
```

t-tests
```{r}
#Marcela final root length
#control v 50
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==0.5, data = exp10, var.equal=FALSE, conf.level=0.95)
#t = 1.7184, df = 32.131, p-value = 0.09535
#control v 100
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==1, data = exp10, var.equal=FALSE, conf.level=0.95)
#t = 2.487, df = 34.917, p-value = 0.01781
#control v 137.5
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==2, data = exp10, var.equal=FALSE, conf.level=0.95)
#t = 3.5242, df = 32.763, p-value = 0.001277
#control v 150
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==10, data = exp10, var.equal=FALSE, conf.level=0.95)
#t = 4.0342, df = 32.122, p-value = 0.0003165
#control v 20
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==20, data = exp10, var.equal=FALSE, conf.level=0.95)
#t = 5.4116, df = 33.429, p-value = 5.269e-06

exp8_rate%>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="200") %>% 
  summary()
```

Data Visualization
```{r}


##Final root length
#Marcela
ggplot(exp10_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  scale_x_discrete(labels = c("", expression(italic(""))))+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Dark2", name = "[ATPƴS] (µM)", labels=c("Control", "0.5", "1", "2", "10", "20"))
ggsave("exp10_finalgrowth.png")
```

