---
title: "exp4_analysis"
author: "Marcela Morassi"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp4_m <- read.csv("exp4_m.csv")
```

Data Manipulation
```{r}
#turning data discrete
exp4_m <- exp4_m %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==7, root>0) %>% 
  mutate(genotype = factor(genotype, levels = c("WT", "KO"))) %>% 
  mutate(ATP_conc = factor(ATP_conc, levels = c("0", "2.5", "5", "7.5", "10")))


#SE
exp4_m_SE <- exp4_m %>% 
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))
```

t-tests
```{r}
#Marcela final root length
#control v 2.5
t.test(root ~ ATP_conc, ATP_conc == 0| ATP_conc ==2.5, data = exp4_m, var.equal=FALSE, conf.level=0.95)
#control v 5
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc == 5, data = exp4_m, var.equal=FALSE, conf.level=0.95)
#control v 7.5
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc == 7.5, data = exp4_m, var.equal=FALSE, conf.level=0.95)
#control v 10
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc == 10, data = exp4_m, var.equal=FALSE, conf.level=0.95)

exp4_m %>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="10") %>% 
  summary()


```

Data Visualization
```{r}


##Final root length
#Marcela
ggplot(exp4_m_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Pastel2", name = "", labels=c("0 µM ATPƴS", "2.5 µM ATPƴS","5 µM ATPƴS",
                                                             "7.5 µM ATPƴS","10 µM ATPƴS"))
ggsave("exp4_m_finalgrowth.png")
```

