---
title: "exp6_analysis"
author: "Marcela Morassi"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp6_m <- read.csv("exp6_data.csv")
```

Data Manipulation
```{r}
#turning data discrete
exp6_m <- exp6_m %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==7, root>0) %>% 
  mutate(genotype = factor(genotype, levels = c("WT", "KO")))


#SE
exp6_m_SE <- exp6_m %>% 
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))
```

t-tests
```{r}
#Marcela final root length
#WT control vs. 137.5
t.test(root ~ ATP_conc, genotype=="WT", data = exp6_m, var.equal=FALSE, conf.level=0.95)
#KO control vs. 137.5
t.test(root ~ ATP_conc, genotype=="KO", data = exp6_m, var.equal=FALSE, conf.level=0.95)
#t = 1.6881, df = 38.557, p-value = 0.09946
#WT control v KO control
t.test(root ~ genotype, ATP_conc == "0", data = exp6_m, var.equal=FALSE, conf.level=0.95)
# = 5.7411, df = 58.698, p-value = 3.512e-07
exp6_m %>% 
  select(root, ATP_conc, genotype) %>% 
  filter(ATP_conc=="0", genotype == "KO") %>% 
  summary()


```

Data Visualization
```{r}


##Final root length
#Marcela
ggplot(exp6_m_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  scale_x_discrete(labels = c("WT", expression(italic("dorn1-1"))))+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Pastel2", name = "", labels=c("Control", "7.5 µM ATPƴS"))
ggsave("exp6_m_finalgrowth.png")
```


