---
title: "exp9_analysis"
output: html_document
date: '2022-04-04'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp9 <- read.csv("exp9_data2.csv")
```

Data Manipulation
```{r}
#turning data discrete
exp9 <- exp9 %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==5, root>0) %>% 
  mutate(genotype = factor(genotype, levels = c("WT", "KO")))


#SE
exp9_SE <- exp9 %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>%
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))
```

t-tests
```{r}
#Marcela final root length
#control v 50
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==50, data = exp9, var.equal=FALSE, conf.level=0.95)
#t = 4.1074, df = 36.385, p-value = 0.000217
#control v 100
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==100, data = exp9, var.equal=FALSE, conf.level=0.95)
#t = 1.6925, df = 33.544, p-value = 0.09982
#control v 137.5
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==137.5, data = exp9, var.equal=FALSE, conf.level=0.95)
#t = 2.292, df = 21.372, p-value = 0.03215
#control v 150
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==200, data = exp9, var.equal=FALSE, conf.level=0.95)
#t = 10.957, df = 38.314, p-value = 2.276e-13
a
#control v 20
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==25, data = exp9, var.equal=FALSE, conf.level=0.95)
#t = 6.3173, df = 37.913, p-value = 2.112e-07

exp9 %>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="200") %>% 
  summary()


```

Data Visualization
```{r}


##Final root length
#Marcela
ggplot(exp9_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  scale_x_discrete(labels = c("", expression(italic("dorn1-1"))))+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Dark2", name = "[ATP] (µM)", labels=c("Control", "25", "50", "100", "137.5", "200"))
ggsave("exp9_finalgrowth.png")
```


