---
title: "exp8_analysis"
author: "Marcela Morassi"
date: "2/7/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")


exp9_data <- read.csv("exp9_data.csv")
```

Data Manipulation
```{r}
#final length
exp9 <- exp9_data %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(day==5, root>0) %>% 
  mutate(ATP_conc = factor(ATP_conc, levels = c("0", "25", "50", "100")))

#SE
exp9_SE <- exp9 %>% 
  group_by(genotype, ATP_conc) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))

#growth rate
exp8_rate <- exp8_data %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  mutate(ATP_conc = factor(ATP_conc, levels = c("0", "50", "100", "137.5", "200")))
#SE
exp8_rate_SE <- exp8_rate %>% 
  group_by(genotype, ATP_conc) %>% 
  drop_na() %>% 
  summarise(mean_growth.rate = mean(growth.rate), se = sd(growth.rate)  / sqrt(n()))
```

final length t-tests
```{r}
#Marcela final root length
#control v 50
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==50, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 1.2132, df = 33.72, p-value = 0.2335
#control v 100
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==100, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 1.8083, df = 35.39, p-value = 0.07907
#control v 137.5
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==137.5, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 1.3127, df = 30.487, p-value = 0.1991
#control v 150
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==150, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 2.0901, df = 36.629, p-value = 0.04361
#control v 20
t.test(root ~ ATP_conc, ATP_conc == 0 | ATP_conc ==20, data = exp7, var.equal=FALSE, conf.level=0.95)
#t = 5.4116, df = 33.429, p-value = 5.269e-06

exp8%>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="150") %>% 
  summary()


```


growth rate t-tests
```{r}
#Marcela final root length
#control v 50
t.test(growth.rate ~ ATP_conc, ATP_conc == 0 | ATP_conc ==50, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 1.7184, df = 32.131, p-value = 0.09535
#control v 100
t.test(growth.rate ~ ATP_conc, ATP_conc == 0 | ATP_conc ==100, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 2.487, df = 34.917, p-value = 0.01781
#control v 137.5
t.test(growth.rate ~ ATP_conc, ATP_conc == 0 | ATP_conc ==137.5, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 3.5242, df = 32.763, p-value = 0.001277
#control v 150
t.test(growth.rate ~ ATP_conc, ATP_conc == 0 | ATP_conc ==200, data = exp8, var.equal=FALSE, conf.level=0.95)
#t = 4.0342, df = 32.122, p-value = 0.0003165
#control v 20
t.test(growth.rate ~ ATP_conc, ATP_conc == 0 | ATP_conc ==20, data = exp7, var.equal=FALSE, conf.level=0.95)
#t = 5.4116, df = 33.429, p-value = 5.269e-06

exp8_rate%>% 
  select(root, ATP_conc) %>% 
  filter(ATP_conc=="200") %>% 
  summary()


```



Data Visualization
```{r}


##Final root length
ggplot(exp9_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("average root length (mm)")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Pastel2", name = "[ATP] (µM)", labels=c("Control", "25", "50","100",
                                                             "137.5","200"))
ggsave("exp9_finalgrowth.png")

##growth rate
ggplot(exp8_rate_SE, aes(x = genotype, y = mean_growth.rate, fill = ATP_conc, group = factor (ATP_conc)), col=palette) +
  geom_col(stat="identity", position = position_dodge())+
  xlab("")+ylab("root growth rate (mm/day)")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  geom_linerange( aes(ymin = mean_growth.rate - se, ymax = mean_growth.rate + se),  width=.2,
                  position=position_dodge(.9))+
  scale_fill_brewer(palette = "Pastel2", name = "[ATP] (µM)", labels=c("Control", "50","100",
                                                             "137.5","200"))
ggsave("exp8_growthrate.png")
```




