---
title: "Experiment_1"
author: "Marcela Morassi"
date: "10/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)
library(dplyr)
library(ggplot2)
library(ggforce)
library(vegan)
library(arules)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")

data1 <- read.csv("data_experiment1_j_noNG.csv")
data1_new <- read.csv("experiment1_j_new.csv")

data2 <- read.csv("jennidata.csv")
```

Amy's set up
```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/MM")
setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/MM")

data1 <- read.csv("data_experiment1_j_noNG.csv")
data1_NG <- read.csv("data_experiment1_j.csv")
data2 <- read.csv("data_experiment1_m_noNG.csv")

```



BarStats Function 
```{r}
#barGraphStats(data=, variable="", byFactorNames=c(""))
barGraphStats <- function(data, variable, byFactorNames) {
  count <- length(byFactorNames)
  N <- aggregate(data[[variable]], data[byFactorNames], FUN=length)
  names(N)[1:count] <- byFactorNames
  names(N) <- sub("^x$", "N", names(N))
  mean <- aggregate(data[[variable]], data[byFactorNames], FUN=mean)
  names(mean)[1:count] <- byFactorNames
  names(mean) <- sub("^x$", "mean", names(mean))
  sd <- aggregate(data[[variable]], data[byFactorNames], FUN=sd)
  names(sd)[1:count] <- byFactorNames
  names(sd) <- sub("^x$", "sd", names(sd))
  preSummaryStats <- merge(N, mean, by=byFactorNames)
  finalSummaryStats <- merge(preSummaryStats, sd, by=byFactorNames)
  finalSummaryStats$se <- finalSummaryStats$sd / sqrt(finalSummaryStats$N)
  return(finalSummaryStats)
}

```


Data Manipulation
```{r}
data1[is.na(data1)] <- 0

#formatting as date
as.Date(data1_new$date_time, "%m/%d/%Y %H:%M")

#making it into a discrete variable
data1_new$ATP_conc_new <- cut(data1_new$ATP_conc, br=c(1,137.5))


data1_KO_control <- data1_new %>% filter(genotype == "KO", day ==7, root>0, ATP_conc ==0)
data1_KO_treatment <- data1_new %>% filter(genotype == "KO", day==7, root>0, ATP_conc >0)
data1_WT_control <- data1_new %>% filter(genotype == "WT", day==7, root>0, ATP_conc ==0)
data1_WT_treatment <- data1_new %>% filter(genotype == "WT", day==7, root>0, ATP_conc >0)

data2_KO_control <- data2 %>% filter(genotype == "KO", day ==7, root>0, ATP_conc ==0)
data2_KO_treatment <- data2 %>% filter(genotype == "KO", day==7, root>0, ATP_conc >0)
data2_WT_control <- data2 %>% filter(genotype == "WT", day==7, root>0, ATP_conc ==0)
data2_WT_treatment <- data2 %>% filter(genotype == "WT", day==7, root>0, ATP_conc >0)


```

Growth Rate
```{r}
data1_new %>% 
  filter(geno_dummy == 0, root>0) %>% 
  ggplot(aes(x=date_time, y = root, color=ATP_dummy)) +
  geom_point()+
  geom_line(aes(group = ATP_dummy)) 


```

Std Error Calcs
```{r}
#KO control exp1 jei
se1 <- sd(data1_KO_control$root)/sqrt(length(data1_KO_control$root))
#KO treatment exp 1
se2 <- sd(data1_KO_treatment$root)/sqrt(length(data1_KO_treatment$root))
#WT control exp 1
se3 <- sd(data1_WT_control$root)/sqrt(length(data1_WT_control$root))
#WT treatment exp 1
se4 <- sd(data1_WT_treatment$root)/sqrt(length(data1_WT_treatment$root))

#KO control marcela
se5 <- sd(data2_KO_control$root)/sqrt(length(data2_KO_control$root))
#KO treatment 
se6 <- sd(data2_KO_treatment$root)/sqrt(length(data2_KO_treatment$root))
#WT control 
se7 <- sd(data2_WT_control$root)/sqrt(length(data2_WT_control$root))
#WT treatment 
se8 <- sd(data2_WT_treatment$root)/sqrt(length(data2_WT_treatment$root))

data1_summary <- data1_new %>% filter(root > 0) %>% 
  aggregate(root ~ ATP_conc,       # Create summary data
                          function(x) c(mean = mean(x),
                                        se = sd(x) / sqrt(length(x))))
data_summary <- data.frame(group = data_summary[ , 1], data_summary$values)
data_summary

```




Significance tests (j)
```{r}

#day7 root length


t.test(root ~ ATP_conc, var.equal=TRUE, data = data1_KO)




t.test(day7_tableWT)

#growth rate
data1_WT_nozero <- data1 %>% filter(genotype == "WT", mean_growthrate > 0)
growthrate_tableWT <- xtabs(mean_growthrate~genotype+ATP_conc,aggregate(mean_growthrate~genotype+ATP_conc,data1_WT_nozero,mean))

t.test(growthrate_tableWT)

data1_KO_nozero <- data1 %>% filter(genotype == "KO", mean_growthrate > 0)
growthrate_tableKO <- xtabs(mean_growthrate~genotype+ATP_conc,aggregate(mean_growthrate~genotype+ATP_conc,data1_KO_nozero,mean))

t.test(growthrate_tableKO)


```


Significance tests (NEW) (j)
```{r}



```


Significance tests (m)
```{r}

#day7 root length
data2_KO <- data2 %>% filter(genotype == "KO", day7_root >0)
day7_tableKO_m <- xtabs(day7_root~genotype+ATP_conc,aggregate(day7_root~genotype+ATP_conc,data2_KO,mean))
day7_tableKO_m

t.test(day7_tableKO_m)

data2_WT <- data2 %>% filter(genotype == "WT", day7_root >0)
day7_tableWT_m <- xtabs(day7_root~genotype+ATP_conc,aggregate(day7_root~genotype+ATP_conc,data2_WT,mean))
day7_tableWT_m

t.test(day7_tableWT_m)

#growth rate
data1_WT_nozero <- data1 %>% filter(genotype == "WT", mean_growthrate > 0)
growthrate_tableWT <- xtabs(mean_growthrate~genotype+ATP_conc,aggregate(mean_growthrate~genotype+ATP_conc,data1_WT_nozero,mean))

t.test(growthrate_tableWT)

data1_KO_nozero <- data1 %>% filter(genotype == "KO", mean_growthrate > 0)
growthrate_tableKO <- xtabs(mean_growthrate~genotype+ATP_conc,aggregate(mean_growthrate~genotype+ATP_conc,data1_KO_nozero,mean))

t.test(growthrate_tableKO)


```


Data visualization
```{r}

#growth rate bar graph
data1 %>% filter(mean_growthrate > 0) %>%  
  ggplot(aes(x = genotype, y = mean_growthrate, fill = ATP_conc, group = factor (ATP_conc))) + geom_bar(stat="identity", position = position_dodge())

ggsave("growthrate_j.png")

data2 %>%  filter (mean_growthrate > 0) %>% 
  ggplot(aes(x = genotype, y = mean_growthrate, fill = ATP_conc, group = factor (ATP_conc))) + geom_bar(stat="identity", position = position_dodge())

ggsave("growthrate_m.png")

#day7 root length bar graph
data1_j_day7 <- data1_new %>% filter(day == 7)
data1_j_day7$genotype <- factor(data1_j_day7$genotype)

data1_new %>% filter(day == 7) %>%  ggplot(aes(x = genotype, y = root, fill = ATP_conc, group = factor (ATP_conc))) + geom_bar(stat="identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=root-se, ymax=root+se),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))

data1_new %>% filter(day == 7) %>%  ggplot(aes(x = genotype, y = root, fill = ATP_conc, group = factor (ATP_conc))) + geom_bar(stat="identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=root-se, ymax=root+se),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))

```


Data Summary
```{r}
sd(data2_KO %>% select(genotype, ATP_conc, day7_root, mean_growthrate) %>% filter(mean_growthrate>0, ATP_conc == 7.5))

data2_WT %>% select(genotype, ATP_conc, day7_root, mean_growthrate) %>% filter(mean_growthrate>0, ATP_conc == 7.5) %>% summary()

data1_WT %>% select(genotype, ATP_conc, day7_root, mean_growthrate) %>% filter(mean_growthrate>0, ATP_conc == 137.5) %>% summary()

```




