---
title: "experiment2_analysis"
author: "Marcela Morassi"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)
library(dplyr)
library(ggplot2)
library(ggforce)
library(vegan)
theme_set(theme_classic()) # Set the theme

setwd("C:/Users/Marcela Morassi/Documents/Github/ClarkLab")

data2_j <- read.csv("exp2_j.csv")
data3_j <- read.csv("data3.csv")

```

Amy's working directory and file setup
```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/MM")
setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/MM")

data2_j <- read.csv("data_experiment2_j_noNG.csv")

```



Data Manipulation
```{r}

#turning data discrete
data2_j <- data2_j %>% 
  mutate(ATP_conc = as.character(ATP_conc)) %>% 
  filter(root>0) %>% 
  mutate(genotype = factor(genotype, levels = c("WT", "KO")))

#SE
exp2_j_SE <- data2_j %>% 
  group_by(genotype, ATP_conc) %>% 
  filter(day==7) %>% 
  summarise(mean_root = mean(root), se = sd(root)  / sqrt(n()))

```

Std Error Calcs
```{r}


```


Growth Rate
```{r}
nested_data_exp2j = data2_j %>% 
  mutate(real_date = as.Date(date_time, "%m/%d/%Y %H:%M")) %>% 
  as_tibble() %>% 
  mutate(full_id = paste(plate_id, seedling, sep = "_")) %>% 
  group_by(full_id, genotype, ATP_conc) %>% 
  arrange(full_id, real_date) %>% 
  select(-plate_id, -seedling) %>% 
  # nest collapses each seedling's data into a separate data frame
  nest()
nested_data_exp2j %>% unnest(data) %>% 
  ggplot(aes(x = real_date, y = root, group = full_id)) + 
  geom_smooth(method = 'lm', se= FALSE) + 
  geom_point() + 
  facet_wrap(~full_id) + cowplot::theme_nothing()

# Define a function that works w/ one group
get_growth_rate = function(data) {
  # Fits a straight line to your root growth data
  regress = lm(root ~ real_date, data = data)
  # Extract the slope of that line (average growth rate)
  regress$coef[2]
}

growth_rates_exp2j = nested_data_exp2j %>% 
  # Create a new column in nested data that contains growth rate
  # map_dbl applies a function (get_growth_rate) to each dataframe in the data column
  # And returns a single numerical value (which is the growth rate)
  mutate(growth_rate = map_dbl(data, get_growth_rate)) %>% 
  select(-data) %>%  # get rid of the nested data
  ungroup()


```

Data visualization
```{r}

#day7 root length bar graph
ggplot(exp1_SE, aes(x = genotype, y = mean_root, fill = ATP_conc, group = factor (ATP_conc))) +
  geom_col(stat="identity", position = position_dodge())+
  geom_linerange( aes(ymin = mean_root - se, ymax = mean_root + se),  width=.2,
                  position=position_dodge(.9))

#growth rate
ggplot(growth_rates_exp2j, aes(x = genotype, y = growth_rate, fill =  ATP_conc)) + 
  geom_boxplot(outlier.shape = NA) +
  coord_cartesian(ylim=c(0,.09))+
  xlab("")+ylab("mean growth rate (mm/day)")+
  scale_x_discrete(labels = c("WT", expression(italic("dorn1-1"))))+
  scale_fill_discrete(name = "", labels=c("0", "7.5 µM ATPƴS"))
ggsave("exp2J_growtrate.png")

nested_data %>% unnest(data) %>% 
  group_by(genotype, ATP_conc) %>% 
  ggplot(aes(x = real_date, y = root, group = full_id, color = ATP_conc)) + 
  geom_smooth(method = 'lm', se= FALSE, alpha = 1/2) + 
  geom_point(alpha = 1/2) + 
  facet_wrap(~genotype)


```

